### PR TITLE
Add iLike query comparison support for postgresql

### PR DESCRIPTION
**Pull request by pedantix**

### CODE REVIEW

**Comment by tanner0101** [comment]
We should include an operator equivalent to `==` as well, like:

```sql
WHERE name ILIKE 'vapor'
```

I'm wondering what the operator for this should be... maybe `=*`?

**Comment by kimdv** [comment]
What is status on this @pedantix ?

**Comment by tanner0101** [comment]
This is possible in Fluent 4 using `.custom` and `.sql`: https://docs.vapor.codes/4.0/fluent/advanced/#sql-custom

**Comment by MrMage** [comment]
Is there a specific reason not to support this directly in Fluent 4?

**Comment by tanner0101** [comment]
@MrMage only PostgreSQL supports the `ILIKE`. Fluent would need a more generalized API for doing this which has yet to be designed. Perhaps computed fields would solve it (by being able to lowercase the field values): https://github.com/vapor/fluent-kit/issues/76

**Pull request closed without merging**
