### PR TITLE
DatabaseConfigurationFactory improvements

### PR DESCRIPTION
**Pull request by ecamacho**
Improves DatabaseConfigurationFactory:

- The `encoder` and `decoder` parameters are forwarded in the function `postgres(url:, maxConnectionsPerEventLoop:, connectionPoolTimeout:, encoder:, decoder:)`
- The `encoder` and `decoder` parameters are forwarded in the function `postgres(hostname:, port:,
username:, password:, database:, tlsConfiguration: , maxConnectionsPerEventLoop:, connectionPoolTimeout:, encoder: , decoder:)`
> Note: Previously, those parameters were not being forwarded in those two functions, thus the default `PostgresDataEncoder` and `PostgresDataDecoder` were being used.

### CODE REVIEW

**Comment by ecamacho** [comment]
@siemensikkema This is still crashing on the Nightly master Linux versions. Seems like a Swift compiler's regression.  The compiler is crashing while trying to compile `CNIOBoringSSL` from `swift-nio-ssl` Can we skip those tests?

**Comment by siemensikkema** [comment]
@ecamacho it seems FluentKit is where it's breaking (fluent-kit/Sources/FluentKit/Enum/EnumBuilder.swift:54:9 - line:65:9) scroll up in the logs and you'll see it. I'm confident it's a swift regression and not something we need to worry about here. I'll discuss with the others what we should do about having these nightly swift versions in the test suite.
Could you phrase the title and PR body such that it is ready for release? See https://github.com/vapor/vapor/blob/master/.github/contributing.md

**Comment by ecamacho** [comment]
@siemensikkema Right, I missed that from the logs. I changed the titles and bodies

**Comment by 0xTim** [comment]
@ecamacho I'm just doing some tidy ups and spotted this! If you want to pull in all the latest changes and get it compiling that should fix both the CI and the merge conflicts and we can get this merged. Sorry it's taken so long to get addressed!

**Comment by gwynne** [comment]
This was fixed at the same time these types were deprecated; those still using the deprecated methods will find they now forward their arguments properly (but should nonetheless switch to the new API).

**Pull request closed without merging**
